// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vnabhadudprtcauddanc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZuYWJoYWR1ZHBydGNhdWRkYW5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MzM0NjEsImV4cCI6MjA3MTIwOTQ2MX0.oblhOX4EoupocD2rR6uU2FDwCQ5zJzQVfG9Hy6vX2ac";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});