// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbovyobqloxiuhdksgls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNib3Z5b2JxbG94aXVoZGtzZ2xzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MjA1MjQsImV4cCI6MjA3Mjk5NjUyNH0.SqFIwuhsJObtiuR86P2fBmfGQx-tB1pHY-Ouk2-fv4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});